###

POST https://localhost:8000/api/login_check HTTP/1.1
Content-Type: application/json

{
    "email": "my@example.com",
    "password": "test"
}

###


###
 
GET https://localhost:8000/home HTTP/1.1
Authorization: Bearer {token}

###